# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vla.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'vla.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvla.proto\x12\x03vla\"\x8d\x01\n\x05Image\x12%\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32\x13.vla.Image.Encoding\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"0\n\x08\x45ncoding\x12\x08\n\x04JPEG\x10\x00\x12\n\n\x06RGB_U8\x10\x01\x12\x0e\n\nF32_RGB_01\x10\x02\"\xcd\x01\n\x0ePredictRequest\x12\x1a\n\x06images\x18\x01 \x03(\x0b\x32\n.vla.Image\x12\x13\n\x0blang_tokens\x18\x02 \x03(\x05\x12\r\n\x05state\x18\x03 \x03(\x02\x12\r\n\x05noise\x18\x04 \x03(\x02\x12\x12\n\nrequest_id\x18\x05 \x01(\x04\x12\x1b\n\x13precomputed_img_emb\x18\x06 \x03(\x02\x12#\n\x1bprecomputed_img_emb_n_views\x18\x07 \x01(\r\x12\x16\n\x0e\x61ttention_mask\x18\x08 \x03(\r\"\x97\x02\n\x0fPredictResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\x14\n\x0c\x61\x63tion_chunk\x18\x02 \x03(\x02\x12\x12\n\nchunk_size\x18\x03 \x01(\r\x12\x12\n\naction_dim\x18\x04 \x01(\r\x12\x18\n\x10latency_ms_total\x18\x05 \x01(\x02\x12\x1c\n\x14latency_ms_inference\x18\x06 \x01(\x02\x12\x1a\n\x12latency_ms_prefill\x18\x08 \x01(\x02\x12\x1a\n\x12latency_ms_denoise\x18\t \x01(\x02\x12\x19\n\x11latency_ms_vision\x18\n \x01(\x02\x12\x18\n\x10latency_ms_queue\x18\x0b \x01(\x02\x12\r\n\x05\x65rror\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vla_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGE']._serialized_start=19
  _globals['_IMAGE']._serialized_end=160
  _globals['_IMAGE_ENCODING']._serialized_start=112
  _globals['_IMAGE_ENCODING']._serialized_end=160
  _globals['_PREDICTREQUEST']._serialized_start=163
  _globals['_PREDICTREQUEST']._serialized_end=368
  _globals['_PREDICTRESPONSE']._serialized_start=371
  _globals['_PREDICTRESPONSE']._serialized_end=650
# @@protoc_insertion_point(module_scope)
